project_id = "vdoncnrhtqxnxtftefod"

[functions.admin-change-password]
verify_jwt = false

[functions.check-license]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.validate-activation-code]
verify_jwt = false

[functions.get-users-with-emails]
verify_jwt = false

[functions.remote-activate-user]
verify_jwt = false

[functions.create-boss-account]
verify_jwt = false

[functions.update-boss-email]
verify_jwt = false

[functions.reset-own-device]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.device-auto-login]
verify_jwt = false
